sudo: false

language: c

install:
  - git clone https://github.com/feeley/gambit.git
  - cd gambit
  - ./configure --prefix=$HOME/gambit
  - make from-scratch
  - make install
  - cd ..
  - git clone https://github.com/fourthbit/ssrun.git
  - cd ssrun
  - PATH="$HOME/gambit/bin/:$PATH" ./install.sh
  - cd ..
  - wget https://raw.githubusercontent.com/fourthbit/spheres/master/.gambini -O ~/.gambini

script:
  - export PATH="$HOME/gambit/bin/:$HOME/ssrun/:$PATH"
  - cd spheres/gambit
  - ./compile-scsc.sh
  - cd ../..
  - ssrun

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/99342bd5365e2eb4774e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
