sudo: required

language: c

install:
  - git clone https://github.com/feeley/gambit.git
  - cd gambit
  - git checkout a831c124d16a3e6496f481b68be180335978e30c
  - ./configure
  - make from-scratch
  - sudo make install
  - cd ..
  - git clone https://github.com/fourthbit/ssrun.git
  - cd ssrun
  - sudo PATH="$PATH:/usr/local/Gambit-C/bin/" ./install.sh
  - cd ..
  - wget https://raw.githubusercontent.com/fourthbit/spheres/master/.gambcini -O ~/.gambcini

script:
  - export PATH="$PATH:/usr/local/Gambit-C/bin/"
  - cd spheres/gambit
  - ./compile-scsc.sh
  - cd ../..
  - ssrun

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/99342bd5365e2eb4774e
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
