Some preliminary checks, using goal-rev ((hs.0 hs.0) (c.0 !p-q))
goal-fwd (h p hs c q hs1) (!h (mp !p !q) !pq-hs !q-c (mp !p-q (mp !q-q (s !h !p-c !q-c))) !pq-hs-h)
just (p phs hs c) ((mp !p-q (mp !q-q (s !h !p-c !q-c))) !pq-hsq !pq-hs-h (-> !h !q-c))

(subset phs.0 hs.0)
(subset a.0 b.0)

((b.0 !pq-hs-h)
 (a.0 !pq-hsq)

 (ws.0 !pq-hsq) ;;; the tail
 (ws.1 !q-hsq)
 (x.0 !q-hsq)
 (qs.0 ())
 (z.0 !q-c)
 (y.0 !p-c)
 (x.1 !h)
 (x.2 (-> !h (-> !p-c !q-c)))
 (ps.0 !q-hsq)
 (y.1 (-> (-> !h !p-c) (-> !h !q-c)))
 (qs.1 !q-hsq)
 (q.0 (s !h !p-c !q-c))
 (p.0 !q-q)
 (x.3 (-> !h !p-c))
 (ps.1 !p-hsq)
 (y.2 (-> !h !q-c))
 (phs.0 !pq-hsq)
 (q.1 (mp !q-q (s !h !p-c !q-c)))
 (p.1 !p-q)
 (c.0 (-> !h !q-c))
 (hs.0 !pq-hs-h)
 (p.2 (mp !p-q (mp !q-q (s !h !p-c !q-c))))
 (hs1.0 !pq-hs-h)
 (hq.0 !q-q)
 (hp.0 !p-q)
 (rcq.0 !q-c)
 (cp.0 !p-c)
 (q.2 (mp !p-q (mp !q-q (s !h !p-c !q-c))))
 (q.3 !q)
 (p.3 !p)
 (h.0 !h)
 (ws.2 !pq-hs)
 (y.3 !q-c)
 (qs.2 !q-hs)
 (x.4 !p-c)
 (ps.2 !p-hs)
 (c.1 !q-c)
 (hs.1 !pq-hs)
 (q.4 !q)
 (p.4 !p)
 (p.5 (mp !p !q))
 (h.1 !h))

(subset a1.0 a1l.0)
(subset a.0 b.0)

((a1l.0 b.0)
 (a.0 !p-hsq)
 (a2.0 !q-hsq)
 (a1.0 !p-hsq)
 (b.1 !pq-hs-h)
 (a.1 !pq-hsq)

 same tail
---
(subset a2.0 a2l.0)
(subset a.0 b.0)

((a2l.0 b.0)
 (a.0 !q-hsq)
 (a1l.0 !p-hs1)
 (a2.0 !q-hsq)
 (a1.0 !p-hsq)
 (b.1 !pq-hs-h)
 (a.1 !pq-hsq)

 same-tail

Check the inductive  case: MP, using goal-fwd ((foo.0 foo.0))
