(define haiku
  '((S 5-line "/  " 7-line "/ " 5-line "- " OrientalName)
    (5-line |1| |4|)
    (5-line |1| |3| |1|)
    (5-line |1| |1| |3|)
    (5-line |1| |2| |2|)
    (5-line |1| |2| |1| |1|)
    (5-line |1| |1| |2| |1|)
    (5-line |1| |1| |1| |2|)
    (5-line |1| |1| |1| |1| |1|)
    (5-line |2| |3|)
    (5-line |2| |2| |1|)
    (5-line |2| |1| |2|)
    (5-line |2| |1| |1| |1|)
    (5-line |3| |2|)
    (5-line |3| |1| |1|)
    (5-line |4| |1|)
    (5-line |5|)
    (7-line |1| |1| 5-line)
    (7-line |2| 5-line)
    (7-line 5-line |1| |1|)
    (7-line 5-line |2|)
    (OrientalName "Basho ")
    (OrientalName "Hokusai ")
    (OrientalName "Makimoto ")
    (OrientalName "Toshiba ")
    (OrientalName "Matsushida ")
    (OrientalName "Yamaha ")
    (|1| "red ")
    (|1| "white ")
    (|1| "black ")
    (|1| "sky ")
    (|1| "dawns ")
    (|1| "breaks ")
    (|1| "falls ")
    (|1| "leaf ")
    (|1| "rain ")
    (|1| "pool ")
    (|1| "my ")
    (|1| "your ")
    (|1| "sun ")
    (|1| "clouds ")
    (|1| "blue ")
    (|1| "green ")
    (|1| "night ")
    (|1| "day ")
    (|1| "dawn ")
    (|1| "dusk ")
    (|1| "birds ")
    (|1| "fly ")
    (|1| "grass ")
    (|1| "tree ")
    (|1| "branch ")
    (|1| "through ")
    (|1| "hell ")
    (|1| "Ada ")
    (|1| "Nick ")
    (|1| "smile ")
    (|1| "grey ")
    (|1| "wave ")
    (|1| "sea ")
    (|1| "to ")
    (|1| "through ")
    (|1| "in ")
    (|1| "no ")
    (|1| "sound ")
    (|1| "mind ")
    (|1| "smoke ")
    (|1| "cranes ")
    (|1| "Zen ")
    (|2| "drifting ")
    (|2| "purple ")
    (|2| "mountains ")
    (|2| "skyline ")
    (|2| "city ")
    (|2| "subway ")
    (|2| "faces ")
    (|2| "empty ")
    (|2| "Buddhist ")
    (|2| "temple ")
    (|2| "Japan ")
    (|2| "ocean ")
    (|2| "thinking ")
    (|2| "zooming ")
    (|2| "rushing ")
    (|2| "over ")
    (|2| "rice fields ")
    (|2| "rising ")
    (|2| "falling ")
    (|2| "hard disk ")
    (|2| "sushi ")
    (|2| "sparkling ")
    (|2| "Tokyo ")
    (|2| "Kyushu ")
    (|2| "Kyoto ")
    (|3| "Parlante ")
    (|3| "sunrises ")
    (|3| "peasant farms ")
    (|3| "computer ")
    (|3| "sashimi ")
    (|3| "juniper ")
    (|3| "fishing boats ")
    (|3| "far away ")
    (|3| "ethernet ")
    (|3| "Mac IP ")
    (|3| "kimonos ")
    (|3| "samurai ")
    (|4| "CD Player ")
    (|4| "Aluminum ")
    (|4| "yakitori ")
    (|4| "Mitsukoshi ")
    (|4| "pampas grass ")
    (|4| "chrysanthemums ")
    (|4| "cherry blossoms ")
    (|5| "resolutional ")
    (|5| "non-elemental ")
    (|5| "rolling foothills rise ")
    (|5| "toward mountains higher ")))
